default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pavel
  password: 12345678
  host: localhost 

development:
  <<: *default
  database: test-guru_development

test:
  <<: *default
  database: test-guru_test

production:
  <<: *default
  database: testguru_production
  username: <%= ENV['TESTGURU_DATABASE_USERNAME'] %>
  password: <%= ENV['TESTGURU_DATABASE_PASSWORD'] %>
