default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  
  
  host: localhost 

development:
  <<: *default
  database: test-guru_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: test-guru_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # database: testguru_production
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>
  